### PR TITLE
Update with master

### PR DESCRIPTION
**Pull request by bolav**
Update from origin

### CODE REVIEW

**Comment by cristeahub** [comment]
How can we test this to make sure it doesn't break our setup?

**Comment by bolav** [comment]
Run `PIPENV_HIDE_EMOJIS=true python3.6 -m pipenv run python manage.py fetch_tollroad_candidates` and see that http://localhost:4002/django/admin/hyre__trip/tollroadcandidate/ is populated.

**Comment by stianjensen** [comment]
Does this require that we update the db model of tollroads candidates to support new fields, or is there no support for fields like "Rushtid morgen, til" yet?

**Comment by bolav** [comment]
No support yet. We are not getting it from the lib, and not saving it yet. I'm waiting for the datamodel of time-support before making that.

**Pull request merged**
